INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Fiebre (aguda)','General',3),
	 ('Fiebre (persistente)','General',4),
	 ('Fiebre (intermitente)','General',4),
	 ('Malestar general','General',4),
	 ('Astenia (cansancio, fatiga, debilidad)','General',4),
	 ('Adinamia (falta de energía)','General',4),
	 ('Pérdida de peso inexplicable','General',3),
	 ('Aumento de peso inexplicable','General',4),
	 ('Anorexia (pérdida de apetito)','General',4),
	 ('Sudoración nocturna','General',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Escalofríos','General',3),
	 ('Dolor (generalizado)','General',3),
	 ('Dolor (localizado)','General',3),
	 ('Dolor (agudo)','General',2),
	 ('Dolor (crónico)','General',4),
	 ('Dolor (inespecífico)','General',4),
	 ('Edema (hinchazón localizada)','General',4),
	 ('Edema (hinchazón generalizada)','General',2),
	 ('Mareo','General',3),
	 ('Vértigo (sensación de giro)','General',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Vértigo (sensación de inestabilidad)','General',3),
	 ('Desmayo','General',2),
	 ('Síncope (pérdida transitoria de conciencia)','General',2),
	 ('Palidez','General',3),
	 ('Ictericia (coloración amarillenta de piel y ojos)','General',2),
	 ('Cianosis (coloración azulada de piel y mucosas)','General',1),
	 ('Linfadenopatías (ganglios inflamados)','General',4),
	 ('Prurito (picazón generalizada)','General',4),
	 ('Prurito (picazón localizada)','General',4),
	 ('Reacción alérgica (rash)','General',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Reacción alérgica (urticaria)','General',3),
	 ('Reacción alérgica (angioedema)','General',1),
	 ('Intolerancia al frío','General',4),
	 ('Intolerancia al calor','General',4),
	 ('Sensación de hormigueo (parestesias)','General',3),
	 ('Entumecimiento','General',3),
	 ('Calambres musculares','General',4),
	 ('Espasmos musculares','General',4),
	 ('Temblor (en reposo)','General',4),
	 ('Temblor (con movimiento)','General',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Rigidez (matutina)','General',4),
	 ('Rigidez (articular)','General',4),
	 ('Sensación de ardor (cutáneo)','General',4),
	 ('Sensación de ardor (interno)','General',3),
	 ('Sensación de opresión (en pecho)','General',2),
	 ('Sensación de opresión (en cabeza)','General',3),
	 ('Sensación de pesadez','General',4),
	 ('Fatiga crónica','General',5),
	 ('Dolor de cabeza (cefalea)','General',3),
	 ('Dolor de cabeza (migraña)','General',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor de cabeza (tensional)','General',4),
	 ('Sensación de "cabeza ligera"','General',3),
	 ('Desequilibrio al caminar','General',3),
	 ('Inestabilidad postural','General',3),
	 ('Sensación de despersonalización/desrealización','General',4),
	 ('Cambios en la voz (sin causa respiratoria aparente)','General',4),
	 ('Ronquidos (sin apnea del sueño confirmada)','General',5),
	 ('Bruxismo (rechinar de dientes)','General',5),
	 ('Sudoración excesiva (hiperhidrosis generalizada)','General',4),
	 ('Sequedad de boca persistente (xerostomía)','General',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Sequedad ocular','General',5),
	 ('Ojos llorosos','General',4),
	 ('Sensibilidad a la luz (fotofobia)','General',3),
	 ('Sensibilidad al sonido (hiperacusia)','General',4),
	 ('Dolor en las articulaciones temporomandibulares (ATM)','General',4),
	 ('Zumbido en los oídos (tinnitus)','General',4),
	 ('Visión de "moscas volantes" (miodesopsias)','General',3),
	 ('Destellos de luz (fotopsias)','General',2),
	 ('Pérdida de visión periférica','General',2),
	 ('Dolor dental (sin causa aparente)','General',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Sangrado de encías','General',4),
	 ('Mal aliento (halitosis)','General',5),
	 ('Úlceras bucales recurrentes','General',4),
	 ('Dolor de garganta crónico (sin infección)','General',5),
	 ('Sensación de nudo en la garganta (globo histérico)','General',4),
	 ('Dificultad para respirar al hablar','General',3),
	 ('Dolor al deglutir líquidos','General',3),
	 ('Dolor al deglutir sólidos','General',3),
	 ('Sensación de ardor en la lengua','General',4),
	 ('Cambios en el color de la lengua','General',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Grietas en las comisuras de la boca (queilitis angular)','General',4),
	 ('Labios secos y agrietados','General',5),
	 ('Dolor en el pecho atípico (no cardíaco)','General',3),
	 ('Dolor en la espalda atípico (no musculoesquelético)','General',3),
	 ('Dolor en las extremidades (sin causa aparente)','General',4),
	 ('Sensación de frío en una extremidad','General',3),
	 ('Sensación de calor en una extremidad','General',3),
	 ('Cambios en el color de la piel de las extremidades','General',3),
	 ('Uñas frágiles','General',5),
	 ('Uñas con estrías','General',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Uñas con manchas','General',5),
	 ('Pelo quebradizo','General',5),
	 ('Pelo graso','General',5),
	 ('Pelo seco','General',5),
	 ('Aparición de canas prematuras','General',5),
	 ('Tos (seca)','Respiratorio',4),
	 ('Tos (productiva)','Respiratorio',4),
	 ('Tos (con flema)','Respiratorio',4),
	 ('Tos (con sangre/hemoptisis)','Respiratorio',1),
	 ('Dificultad para respirar (disnea)','Respiratorio',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dificultad para respirar (de esfuerzo)','Respiratorio',3),
	 ('Dificultad para respirar (en reposo)','Respiratorio',1),
	 ('Dificultad para respirar (nocturna)','Respiratorio',2),
	 ('Sibilancias (silbidos al respirar)','Respiratorio',2),
	 ('Dolor de garganta (odinofagia)','Respiratorio',4),
	 ('Ronquera','Respiratorio',4),
	 ('Disfonía','Respiratorio',4),
	 ('Congestión nasal','Respiratorio',5),
	 ('Secreción nasal (rinorrea)','Respiratorio',5),
	 ('Estornudos','Respiratorio',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor en el pecho al respirar (pleurítico)','Respiratorio',3),
	 ('Opresión en el pecho','Respiratorio',2),
	 ('Respiración ruidosa (estridor)','Respiratorio',1),
	 ('Respiración ruidosa (roncus)','Respiratorio',3),
	 ('Apnea del sueño (sospecha)','Respiratorio',4),
	 ('Pausas respiratorias','Respiratorio',2),
	 ('Dolor en los senos paranasales','Respiratorio',4),
	 ('Pérdida del olfato (anosmia)','Respiratorio',5),
	 ('Voz alterada','Respiratorio',4),
	 ('Sensación de cuerpo extraño en la garganta','Respiratorio',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Tiraje intercostal/subcostal (en niños)','Respiratorio',2),
	 ('Aleteo nasal (en niños)','Respiratorio',2),
	 ('Cianosis perioral (alrededor de la boca)','Respiratorio',1),
	 ('Dolor abdominal (tipo)','Gastrointestinal',3),
	 ('Dolor abdominal (localización)','Gastrointestinal',3),
	 ('Dolor abdominal (irradiación)','Gastrointestinal',3),
	 ('Dolor abdominal (cólico)','Gastrointestinal',3),
	 ('Dolor abdominal (punzante)','Gastrointestinal',3),
	 ('Náuseas','Gastrointestinal',4),
	 ('Vómitos','Gastrointestinal',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Vómitos (en proyectil)','Gastrointestinal',2),
	 ('Vómitos (con sangre/hematemesis)','Gastrointestinal',1),
	 ('Diarrea (aguda)','Gastrointestinal',3),
	 ('Diarrea (crónica)','Gastrointestinal',4),
	 ('Diarrea (con sangre/hematoquecia)','Gastrointestinal',2),
	 ('Diarrea (con moco)','Gastrointestinal',4),
	 ('Diarrea (esteatorrea)','Gastrointestinal',4),
	 ('Estreñimiento (crónico)','Gastrointestinal',5),
	 ('Estreñimiento (agudo)','Gastrointestinal',4),
	 ('Estreñimiento (con esfuerzo)','Gastrointestinal',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Acidez estomacal (pirosis)','Gastrointestinal',4),
	 ('Reflujo gastroesofágico','Gastrointestinal',4),
	 ('Indigestión','Gastrointestinal',4),
	 ('Dispepsia','Gastrointestinal',4),
	 ('Hinchazón abdominal','Gastrointestinal',4),
	 ('Distensión abdominal','Gastrointestinal',3),
	 ('Gases (flatulencias)','Gastrointestinal',5),
	 ('Gases (eructos frecuentes)','Gastrointestinal',5),
	 ('Sangre en las heces (melena - heces negras)','Gastrointestinal',2),
	 ('Sangre en las heces (hematoquecia - sangre roja)','Gastrointestinal',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Cambios en el hábito intestinal','Gastrointestinal',3),
	 ('Dolor al defecar','Gastrointestinal',4),
	 ('Hemorroides (sangrado)','Gastrointestinal',4),
	 ('Hemorroides (dolor)','Gastrointestinal',4),
	 ('Hemorroides (prolapso)','Gastrointestinal',4),
	 ('Fisura anal (dolor)','Gastrointestinal',4),
	 ('Fisura anal (sangrado)','Gastrointestinal',4),
	 ('Dificultad para tragar (disfagia)','Gastrointestinal',2),
	 ('Dificultad para tragar (para sólidos)','Gastrointestinal',3),
	 ('Dificultad para tragar (para líquidos)','Gastrointestinal',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor al tragar (odinofagia)','Gastrointestinal',4),
	 ('Masa abdominal palpable','Gastrointestinal',2),
	 ('Heces pálidas (acolia)','Gastrointestinal',3),
	 ('Orina oscura (coluria)','Gastrointestinal',3),
	 ('Ruidos intestinales aumentados','Gastrointestinal',4),
	 ('Ruidos intestinales disminuidos','Gastrointestinal',3),
	 ('Dolor en el hipocondrio derecho','Gastrointestinal',3),
	 ('Dolor en el hipocondrio izquierdo','Gastrointestinal',3),
	 ('Dolor en el epigastrio','Gastrointestinal',3),
	 ('Regurgitación','Gastrointestinal',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Sensación de plenitud postprandial','Gastrointestinal',5),
	 ('Dolor perianal','Gastrointestinal',4),
	 ('Dolor en el pecho (angina)','Cardiovascular',2),
	 ('Dolor en el pecho (opresivo)','Cardiovascular',2),
	 ('Dolor en el pecho (punzante)','Cardiovascular',3),
	 ('Dolor en el pecho (irradiado)','Cardiovascular',2),
	 ('Palpitaciones (sensación de latidos rápidos)','Cardiovascular',2),
	 ('Palpitaciones (sensación de latidos fuertes)','Cardiovascular',3),
	 ('Palpitaciones (sensación de latidos irregulares)','Cardiovascular',2),
	 ('Falta de aire (disnea de esfuerzo)','Cardiovascular',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Falta de aire (en reposo)','Cardiovascular',1),
	 ('Ortopnea (dificultad para respirar acostado)','Cardiovascular',2),
	 ('Disnea paroxística nocturna','Cardiovascular',2),
	 ('Hinchazón de piernas (edema)','Cardiovascular',3),
	 ('Hinchazón de tobillos (edema)','Cardiovascular',3),
	 ('Edema (bilateral)','Cardiovascular',3),
	 ('Edema (unilateral)','Cardiovascular',3),
	 ('Cansancio fácil (fatiga cardiovascular)','Cardiovascular',4),
	 ('Mareos (de origen cardiovascular)','Cardiovascular',2),
	 ('Síncope (pérdida de conciencia de origen cardiovascular)','Cardiovascular',1);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Presión arterial alta (síntomas de crisis hipertensiva)','Cardiovascular',2),
	 ('Presión arterial baja (síntomas de hipotensión)','Cardiovascular',2),
	 ('Dolor en las pantorrillas al caminar (claudicación intermitente)','Cardiovascular',4),
	 ('Venas varicosas (dolor)','Cardiovascular',4),
	 ('Venas varicosas (pesadez)','Cardiovascular',5),
	 ('Venas varicosas (hinchazón)','Cardiovascular',4),
	 ('Cianosis (coloración azulada)','Cardiovascular',1),
	 ('Dolor en el brazo izquierdo (irradiado)','Cardiovascular',2),
	 ('Dolor en la mandíbula (irradiado)','Cardiovascular',2),
	 ('Sudoración fría (asociada a dolor torácico)','Cardiovascular',1);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor de espalda con síntomas cardíacos (irradiado)','Cardiovascular',2),
	 ('Desmayo al levantarse (hipotensión ortostática)','Cardiovascular',3),
	 ('Sensación de opresión en el cuello (de origen cardíaco)','Cardiovascular',2),
	 ('Pulso irregular','Cardiovascular',2),
	 ('Pulso débil','Cardiovascular',1),
	 ('Dedos fríos y pálidos (fenómeno de Raynaud)','Cardiovascular',4),
	 ('Dolor al orinar (disuria)','Urológico/Renal',3),
	 ('Dolor al orinar (ardor)','Urológico/Renal',3),
	 ('Orinar con mucha frecuencia (polaquiuria)','Urológico/Renal',3),
	 ('Necesidad urgente de orinar (tenesmo vesical)','Urológico/Renal',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Orinar por la noche (nicturia)','Urológico/Renal',4),
	 ('Sangre en la orina (hematuria macroscópica)','Urológico/Renal',2),
	 ('Sangre en la orina (hematuria microscópica)','Urológico/Renal',3),
	 ('Orina turbia','Urológico/Renal',4),
	 ('Orina con mal olor','Urológico/Renal',4),
	 ('Incontinencia urinaria (de esfuerzo)','Urológico/Renal',5),
	 ('Incontinencia urinaria (de urgencia)','Urológico/Renal',4),
	 ('Incontinencia urinaria (por rebosamiento)','Urológico/Renal',3),
	 ('Dificultad para iniciar la micción (vacilación)','Urológico/Renal',4),
	 ('Chorro urinario débil','Urológico/Renal',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Chorro urinario intermitente','Urológico/Renal',4),
	 ('Dolor en la zona lumbar (flanco unilateral)','Urológico/Renal',2),
	 ('Dolor en la zona lumbar (flanco bilateral)','Urológico/Renal',3),
	 ('Retención urinaria (incapacidad para vaciar la vejiga)','Urológico/Renal',2),
	 ('Dolor testicular','Urológico/Renal',2),
	 ('Hinchazón escrotal','Urológico/Renal',2),
	 ('Eyaculación dolorosa','Urológico/Renal',4),
	 ('Disfunción eréctil','Urológico/Renal',5),
	 ('Cambios en el volumen de orina (poliuria)','Urológico/Renal',4),
	 ('Cambios en el volumen de orina (oliguria)','Urológico/Renal',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Cambios en el volumen de orina (anuria)','Urológico/Renal',1),
	 ('Dolor suprapúbico','Urológico/Renal',3),
	 ('Dolor en la uretra','Urológico/Renal',4),
	 ('Secreción uretral','Urológico/Renal',3),
	 ('Prurito genital (masculino)','Urológico/Renal',4),
	 ('Masa en los testículos','Urológico/Renal',3),
	 ('Dolor en el pene','Urológico/Renal',3),
	 ('Priapismo (erección prolongada y dolorosa)','Urológico/Renal',2),
	 ('Retraso menstrual','Ginecológico/Obstétrico',4),
	 ('Amenorrea (ausencia de menstruación)','Ginecológico/Obstétrico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Sangrado vaginal anormal (metrorragia - sangrado irregular)','Ginecológico/Obstétrico',3),
	 ('Sangrado vaginal anormal (menorragia - sangrado abundante)','Ginecológico/Obstétrico',2),
	 ('Dolor menstrual intenso (dismenorrea)','Ginecológico/Obstétrico',4),
	 ('Dolor pélvico crónico','Ginecológico/Obstétrico',4),
	 ('Secreción vaginal anormal (flujo)','Ginecológico/Obstétrico',4),
	 ('Secreción vaginal anormal (olor)','Ginecológico/Obstétrico',4),
	 ('Secreción vaginal anormal (color)','Ginecológico/Obstétrico',4),
	 ('Secreción vaginal anormal (picazón/prurito)','Ginecológico/Obstétrico',4),
	 ('Dolor durante las relaciones sexuales (dispareunia)','Ginecológico/Obstétrico',4),
	 ('Bulto en el seno','Ginecológico/Obstétrico',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor en el seno (mastalgia)','Ginecológico/Obstétrico',4),
	 ('Cambios en el pezón (secreción)','Ginecológico/Obstétrico',3),
	 ('Cambios en el pezón (retracción)','Ginecológico/Obstétrico',3),
	 ('Náuseas en el embarazo','Ginecológico/Obstétrico',4),
	 ('Vómitos en el embarazo (hiperemesis gravídica)','Ginecológico/Obstétrico',3),
	 ('Sangrado en el embarazo (amenaza de aborto)','Ginecológico/Obstétrico',2),
	 ('Sangrado en el embarazo (desprendimiento)','Ginecológico/Obstétrico',1),
	 ('Contracciones (prematuras)','Ginecológico/Obstétrico',2),
	 ('Contracciones (de parto)','Ginecológico/Obstétrico',2),
	 ('Disminución de movimientos fetales','Ginecológico/Obstétrico',1);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Hinchazón en el embarazo (edema manos)','Ginecológico/Obstétrico',3),
	 ('Hinchazón en el embarazo (edema cara)','Ginecológico/Obstétrico',3),
	 ('Hinchazón en el embarazo (edema piernas)','Ginecológico/Obstétrico',4),
	 ('Dolor de cabeza en el embarazo (sospecha de preeclampsia)','Ginecológico/Obstétrico',2),
	 ('Pérdida de líquido amniótico','Ginecológico/Obstétrico',1),
	 ('Fiebre en el embarazo','Ginecológico/Obstétrico',2),
	 ('Síntomas de menopausia (sofocos)','Ginecológico/Obstétrico',5),
	 ('Síntomas de menopausia (sequedad vaginal)','Ginecológico/Obstétrico',5),
	 ('Síntomas de menopausia (cambios de humor)','Ginecológico/Obstétrico',5),
	 ('Sangrado postmenopáusico','Ginecológico/Obstétrico',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor en la pelvis','Ginecológico/Obstétrico',3),
	 ('Dolor en los ovarios','Ginecológico/Obstétrico',3),
	 ('Sensación de peso en la pelvis (prolapso)','Ginecológico/Obstétrico',4),
	 ('Dolor en la vulva','Ginecológico/Obstétrico',4),
	 ('Úlceras genitales (femeninas)','Ginecológico/Obstétrico',4),
	 ('Verrugas genitales (femeninas)','Ginecológico/Obstétrico',5),
	 ('Dolor en el bajo vientre (ginecológico)','Ginecológico/Obstétrico',3),
	 ('Cambios en el ciclo menstrual (irregularidades)','Ginecológico/Obstétrico',4),
	 ('Dolor de espalda (lumbalgia)','Musculoesquelético',4),
	 ('Dolor de espalda (cervicalgia)','Musculoesquelético',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor de espalda (dorsalgia)','Musculoesquelético',4),
	 ('Dolor de espalda (ciática)','Musculoesquelético',3),
	 ('Dolor articular (artralgia)','Musculoesquelético',4),
	 ('Dolor articular (en una articulación)','Musculoesquelético',4),
	 ('Dolor articular (en varias articulaciones)','Musculoesquelético',4),
	 ('Hinchazón articular (artritis)','Musculoesquelético',3),
	 ('Hinchazón articular (con calor)','Musculoesquelético',3),
	 ('Hinchazón articular (con enrojecimiento)','Musculoesquelético',3),
	 ('Rigidez articular (matutina)','Musculoesquelético',4),
	 ('Rigidez articular (post-reposo)','Musculoesquelético',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor muscular (mialgia)','Musculoesquelético',4),
	 ('Dolor muscular (localizado)','Musculoesquelético',4),
	 ('Dolor muscular (generalizado)','Musculoesquelético',4),
	 ('Calambres musculares','Musculoesquelético',4),
	 ('Debilidad muscular (generalizada)','Musculoesquelético',2),
	 ('Debilidad muscular (localizada)','Musculoesquelético',3),
	 ('Limitación del movimiento (articular)','Musculoesquelético',3),
	 ('Limitación del movimiento (muscular)','Musculoesquelético',3),
	 ('Dolor post-golpe','Musculoesquelético',3),
	 ('Dolor post-caída','Musculoesquelético',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor post-esguince','Musculoesquelético',3),
	 ('Dolor post-fractura','Musculoesquelético',2),
	 ('Hinchazón post-traumatismo','Musculoesquelético',3),
	 ('Deformidad post-traumatismo','Musculoesquelético',2),
	 ('Dolor en el cuello (tortícolis)','Musculoesquelético',4),
	 ('Dolor en el hombro (tendinitis)','Musculoesquelético',4),
	 ('Dolor en el hombro (bursitis)','Musculoesquelético',4),
	 ('Dolor en el codo (epicondilitis)','Musculoesquelético',4),
	 ('Dolor en el codo (epitrocleítis)','Musculoesquelético',4),
	 ('Dolor en la muñeca (síndrome del túnel carpiano)','Musculoesquelético',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor en la mano / dedos (artritis)','Musculoesquelético',4),
	 ('Dolor en la mano / dedos (tendinitis)','Musculoesquelético',4),
	 ('Dolor en la cadera','Musculoesquelético',3),
	 ('Dolor en la rodilla (meniscal)','Musculoesquelético',3),
	 ('Dolor en la rodilla (ligamentoso)','Musculoesquelético',3),
	 ('Dolor en el tobillo (esguince)','Musculoesquelético',3),
	 ('Dolor en el tobillo (tendinitis)','Musculoesquelético',4),
	 ('Dolor en el pie / dedos del pie (fascitis plantar)','Musculoesquelético',4),
	 ('Dolor en el pie / dedos del pie (juanete)','Musculoesquelético',5),
	 ('Deformidad articular','Musculoesquelético',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Chasquidos articulares','Musculoesquelético',5),
	 ('Sensación de inestabilidad articular','Musculoesquelético',3),
	 ('Dolor al cargar peso','Musculoesquelético',4),
	 ('Dolor al mover la articulación','Musculoesquelético',4),
	 ('Dolor que empeora con la actividad','Musculoesquelético',4),
	 ('Dolor que mejora con el reposo','Musculoesquelético',4),
	 ('Dolor nocturno (musculoesquelético)','Musculoesquelético',4),
	 ('Contracturas musculares','Musculoesquelético',4),
	 ('Nódulos musculares','Musculoesquelético',4),
	 ('Sensación de quemazón en las articulaciones','Musculoesquelético',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dolor de cabeza (cefalea neurológica)','Neurológico',3),
	 ('Dolor de cabeza (migraña neurológica)','Neurológico',3),
	 ('Dolor de cabeza (tensional neurológica)','Neurológico',4),
	 ('Dolor de cabeza (en trueno)','Neurológico',1),
	 ('Mareos (neurológico)','Neurológico',3),
	 ('Vértigo (sensación de giro neurológico)','Neurológico',3),
	 ('Vértigo (inestabilidad neurológica)','Neurológico',3),
	 ('Desmayo (neurológico)','Neurológico',2),
	 ('Síncope (pérdida de conciencia neurológica)','Neurológico',1),
	 ('Convulsiones (generalizadas)','Neurológico',1);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Convulsiones (focales)','Neurológico',2),
	 ('Crisis epilépticas','Neurológico',1),
	 ('Pérdida de conciencia (sin convulsiones)','Neurológico',2),
	 ('Debilidad en una parte del cuerpo (hemiparesia)','Neurológico',1),
	 ('Debilidad en una parte del cuerpo (monoparesia)','Neurológico',2),
	 ('Parálisis (hemiplejia)','Neurológico',1),
	 ('Parálisis (paraplejia)','Neurológico',1),
	 ('Parálisis (cuadriplejia)','Neurológico',1),
	 ('Dificultad para hablar (disartria)','Neurológico',2),
	 ('Dificultad para hablar (afasia expresiva)','Neurológico',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dificultad para hablar (afasia receptiva)','Neurológico',2),
	 ('Problemas de visión (visión borrosa neurológica)','Neurológico',2),
	 ('Problemas de visión (visión doble/diplopía neurológica)','Neurológico',2),
	 ('Problemas de visión (pérdida súbita de visión)','Neurológico',1),
	 ('Problemas de visión (pérdida progresiva de visión)','Neurológico',3),
	 ('Entumecimiento (parestesias)','Neurológico',3),
	 ('Entumecimiento (en extremidades)','Neurológico',3),
	 ('Entumecimiento (en cara)','Neurológico',2),
	 ('Hormigueo (parestesias)','Neurológico',3),
	 ('Hormigueo (en extremidades)','Neurológico',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Hormigueo (en cara)','Neurológico',2),
	 ('Temblor (de reposo)','Neurológico',4),
	 ('Temblor (de acción)','Neurológico',4),
	 ('Temblor (postural)','Neurológico',4),
	 ('Problemas de equilibrio (ataxia)','Neurológico',2),
	 ('Marcha inestable (ataxia)','Neurológico',2),
	 ('Pérdida de memoria (amnesia anterógrada)','Neurológico',3),
	 ('Pérdida de memoria (amnesia retrógrada)','Neurológico',3),
	 ('Confusión','Neurológico',2),
	 ('Desorientación (temporal)','Neurológico',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Desorientación (espacial)','Neurológico',2),
	 ('Desorientación (personal)','Neurológico',2),
	 ('Cambios en la personalidad (neurológico)','Neurológico',3),
	 ('Insomnio (de origen neurológico)','Neurológico',4),
	 ('Somnolencia excesiva (de origen neurológico)','Neurológico',3),
	 ('Dolor neuropático (ardor)','Neurológico',4),
	 ('Dolor neuropático (punzante)','Neurológico',4),
	 ('Dolor neuropático (eléctrico)','Neurológico',4),
	 ('Tics nerviosos (motores)','Neurológico',4),
	 ('Tics nerviosos (vocales)','Neurológico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Vértigo posicional (benigno paroxístico)','Neurológico',3),
	 ('Parálisis facial (Bell)','Neurológico',2),
	 ('Alteración del gusto','Neurológico',4),
	 ('Alteración del olfato','Neurológico',4),
	 ('Pérdida de audición (hipoacusia)','Neurológico',4),
	 ('Zumbido en los oídos (tinnitus neurológico)','Neurológico',4),
	 ('Sensación de cabeza hueca','Neurológico',4),
	 ('Sensación de presión en la cabeza','Neurológico',3),
	 ('Sensación de hormigueo en la cara','Neurológico',2),
	 ('Sensación de quemazón en la piel (neurológica)','Neurológico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dificultad para coordinar movimientos (disdiadococinesia)','Neurológico',3),
	 ('Disfagia (de origen neurológico)','Neurológico',2),
	 ('Diplopía (visión doble)','Neurológico',2),
	 ('Nistagmo (movimientos oculares involuntarios)','Neurológico',2),
	 ('Erupción cutánea (rash)','Dermatológico',4),
	 ('Erupción cutánea (maculopapular)','Dermatológico',4),
	 ('Erupción cutánea (vesicular)','Dermatológico',4),
	 ('Erupción cutánea (pustular)','Dermatológico',4),
	 ('Picazón (prurito cutáneo)','Dermatológico',4),
	 ('Picazón (localizado cutáneo)','Dermatológico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Picazón (generalizado cutáneo)','Dermatológico',4),
	 ('Enrojecimiento de la piel (eritema localizado)','Dermatológico',4),
	 ('Enrojecimiento de la piel (eritema difuso)','Dermatológico',3),
	 ('Lesiones en la piel (ampollas)','Dermatológico',3),
	 ('Lesiones en la piel (pústulas)','Dermatológico',3),
	 ('Lesiones en la piel (úlceras)','Dermatológico',3),
	 ('Lesiones en la piel (nódulos)','Dermatológico',3),
	 ('Lesiones en la piel (pápulas)','Dermatológico',4),
	 ('Lesiones en la piel (placas)','Dermatológico',4),
	 ('Cambios en lunares (tamaño)','Dermatológico',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Cambios en lunares (forma)','Dermatológico',3),
	 ('Cambios en lunares (color)','Dermatológico',3),
	 ('Cambios en lunares (picazón)','Dermatológico',3),
	 ('Cambios en lunares (sangrado)','Dermatológico',3),
	 ('Cambios en lunares (asimetría)','Dermatológico',3),
	 ('Cambios en lunares (bordes irregulares)','Dermatológico',3),
	 ('Acné (comedones)','Dermatológico',5),
	 ('Acné (pápulas)','Dermatológico',5),
	 ('Acné (pústulas)','Dermatológico',5),
	 ('Acné (quistes)','Dermatológico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Dermatitis (eczema)','Dermatológico',4),
	 ('Dermatitis (atópica)','Dermatológico',4),
	 ('Dermatitis (de contacto)','Dermatológico',4),
	 ('Dermatitis (seborreica)','Dermatológico',4),
	 ('Psoriasis (placas eritematoescamosas)','Dermatológico',4),
	 ('Urticaria (habones)','Dermatológico',3),
	 ('Urticaria (angioedema)','Dermatológico',1),
	 ('Hongos en la piel / uñas (micosis)','Dermatológico',5),
	 ('Hongos en las uñas (onicomicosis)','Dermatológico',5),
	 ('Infecciones bacterianas de la piel (impétigo)','Dermatológico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Infecciones bacterianas de la piel (celulitis)','Dermatológico',3),
	 ('Infecciones bacterianas de la piel (erisipela)','Dermatológico',3),
	 ('Infecciones bacterianas de la piel (forúnculos)','Dermatológico',4),
	 ('Verrugas (comunes)','Dermatológico',5),
	 ('Verrugas (plantares)','Dermatológico',5),
	 ('Verrugas (genitales)','Dermatológico',5),
	 ('Herpes (labial)','Dermatológico',4),
	 ('Herpes (zóster)','Dermatológico',3),
	 ('Herpes (genital)','Dermatológico',4),
	 ('Quemaduras (dolor)','Dermatológico',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Quemaduras (enrojecimiento)','Dermatológico',3),
	 ('Quemaduras (ampollas)','Dermatológico',2),
	 ('Quemaduras (necrosis)','Dermatológico',1),
	 ('Picaduras de insectos (reacción local)','Dermatológico',4),
	 ('Picaduras de insectos (reacción sistémica)','Dermatológico',1),
	 ('Reacciones alérgicas en la piel (por contacto)','Dermatológico',4),
	 ('Reacciones alérgicas en la piel (por fármacos)','Dermatológico',3),
	 ('Caída del cabello (alopecia difusa)','Dermatológico',5),
	 ('Caída del cabello (alopecia areata)','Dermatológico',5),
	 ('Uñas quebradizas / con cambios (color)','Dermatológico',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Uñas quebradizas / con cambios (forma)','Dermatológico',5),
	 ('Uñas quebradizas / con cambios (engrosamiento)','Dermatológico',5),
	 ('Piel seca (xerosis)','Dermatológico',5),
	 ('Piel grasa (seborrea)','Dermatológico',5),
	 ('Sudoración excesiva (hiperhidrosis localizada)','Dermatológico',5),
	 ('Quistes sebáceos','Dermatológico',5),
	 ('Lipomas','Dermatológico',5),
	 ('Cicatrices anormales (queloides)','Dermatológico',5),
	 ('Cicatrices anormales (hipertróficas)','Dermatológico',5),
	 ('Decoloración de la piel (hipopigmentación)','Dermatológico',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Decoloración de la piel (hiperpigmentación)','Dermatológico',5),
	 ('Decoloración de la piel (vitíligo)','Dermatológico',5),
	 ('Úlceras por presión','Dermatológico',3),
	 ('Piel escamosa','Dermatológico',4),
	 ('Piel agrietada','Dermatológico',4),
	 ('Piel sensible','Dermatológico',5),
	 ('Ampollas por fricción','Dermatológico',4),
	 ('Rosácea (enrojecimiento facial)','Dermatológico',4),
	 ('Rosácea (pápulas)','Dermatológico',4),
	 ('Rosácea (pústulas)','Dermatológico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Nevus (aparición)','Dermatológico',4),
	 ('Nevus (cambio)','Dermatológico',3),
	 ('Queratosis seborreica','Dermatológico',5),
	 ('Queratosis actínica','Dermatológico',4),
	 ('Carcinoma basocelular (sospecha)','Dermatológico',3),
	 ('Carcinoma espinocelular (sospecha)','Dermatológico',3),
	 ('Melanoma (sospecha)','Dermatológico',2),
	 ('Erisipela','Dermatológico',3),
	 ('Foliculitis','Dermatológico',4),
	 ('Abscesos cutáneos','Dermatológico',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Fiebre en lactantes','Pediátrico',2),
	 ('Fiebre en niños (sin foco aparente)','Pediátrico',3),
	 ('Irritabilidad en lactantes','Pediátrico',2),
	 ('Llanto inconsolable','Pediátrico',3),
	 ('Rechazo del alimento (pediátrico)','Pediátrico',3),
	 ('Dificultad para alimentarse (pediátrico)','Pediátrico',3),
	 ('Vómitos en proyectil (pediátrico)','Pediátrico',2),
	 ('Diarrea en niños (con signos de deshidratación)','Pediátrico',2),
	 ('Estreñimiento en niños (crónico)','Pediátrico',4),
	 ('Estreñimiento en niños (doloroso)','Pediátrico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Erupciones cutáneas infantiles (exantemas virales)','Pediátrico',4),
	 ('Erupción cutánea (varicela)','Pediátrico',4),
	 ('Erupción cutánea (sarampión)','Pediátrico',3),
	 ('Erupción cutánea (rubéola)','Pediátrico',4),
	 ('Erupción cutánea (eritema infeccioso)','Pediátrico',4),
	 ('Tos persistente en niños','Pediátrico',3),
	 ('Dificultad respiratoria en niños (tiraje)','Pediátrico',1),
	 ('Dificultad respiratoria en niños (aleteo nasal)','Pediátrico',1),
	 ('Dificultad respiratoria en niños (quejido)','Pediátrico',1),
	 ('Convulsiones febriles','Pediátrico',1);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Retraso en el desarrollo (motor grueso)','Pediátrico',5),
	 ('Retraso en el desarrollo (motor fino)','Pediátrico',5),
	 ('Retraso en el desarrollo (del lenguaje)','Pediátrico',5),
	 ('Retraso en el desarrollo (cognitivo)','Pediátrico',5),
	 ('Retraso en el desarrollo (social)','Pediátrico',5),
	 ('Problemas de aprendizaje (dificultad escolar)','Pediátrico',5),
	 ('Problemas de conducta (agresividad infantil)','Pediátrico',5),
	 ('Problemas de conducta (hiperactividad infantil)','Pediátrico',5),
	 ('Problemas de conducta (retraimiento infantil)','Pediátrico',5),
	 ('Enuresis (mojar la cama)','Pediátrico',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Enuresis (primaria)','Pediátrico',5),
	 ('Enuresis (secundaria)','Pediátrico',5),
	 ('Encopresis (defecación involuntaria)','Pediátrico',5),
	 ('Dolor abdominal recurrente en niños','Pediátrico',4),
	 ('Otitis media aguda (dolor de oído pediátrico)','Pediátrico',3),
	 ('Otitis media aguda (fiebre pediátrica)','Pediátrico',3),
	 ('Otitis media aguda (irritabilidad pediátrica)','Pediátrico',3),
	 ('Faringoamigdalitis (dolor de garganta pediátrico)','Pediátrico',4),
	 ('Faringoamigdalitis (fiebre pediátrica)','Pediátrico',3),
	 ('Faringoamigdalitis (dificultad para tragar pediátrica)','Pediátrico',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Pediculosis (piojos, picazón en el cuero cabelludo)','Pediátrico',5),
	 ('Escabiosis (sarna, picazón intensa, lesiones cutáneas)','Pediátrico',4),
	 ('Ictericia neonatal (coloración amarilla en recién nacidos)','Pediátrico',2),
	 ('Reflujo gastroesofágico en lactantes (regurgitaciones frecuentes)','Pediátrico',4),
	 ('Reflujo gastroesofágico en lactantes (irritabilidad)','Pediátrico',4),
	 ('Cólico del lactante (llanto excesivo)','Pediátrico',4),
	 ('Cólico del lactante (irritabilidad)','Pediátrico',4),
	 ('Bronquiolitis (tos, sibilancias, dificultad respiratoria en lactantes)','Pediátrico',2),
	 ('Crup (laringotraqueobronquitis, tos perruna, estridor)','Pediátrico',2),
	 ('Dolor de crecimiento (dolor en extremidades inferiores)','Pediátrico',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Problemas de visión en niños (estrabismo)','Pediátrico',5),
	 ('Problemas de visión en niños (ambliopía)','Pediátrico',5),
	 ('Problemas de visión en niños (dificultad para ver la pizarra)','Pediátrico',5),
	 ('Problemas de audición en niños (no responde a sonidos)','Pediátrico',5),
	 ('Problemas de audición en niños (retraso del lenguaje)','Pediátrico',5),
	 ('Anemia en niños (palidez)','Pediátrico',4),
	 ('Anemia en niños (cansancio)','Pediátrico',4),
	 ('Obesidad infantil','Pediátrico',5),
	 ('Bajo peso (pediátrico)','Pediátrico',5),
	 ('Desnutrición (pediátrico)','Pediátrico',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Talla baja (pediátrico)','Pediátrico',5),
	 ('Retraso de crecimiento (pediátrico)','Pediátrico',5),
	 ('Pubertad precoz','Pediátrico',5),
	 ('Pubertad retrasada','Pediátrico',5),
	 ('Problemas de sueño en niños (insomnio)','Pediátrico',5),
	 ('Problemas de sueño en niños (despertares nocturnos)','Pediátrico',5),
	 ('Problemas de sueño en niños (pesadillas)','Pediátrico',5),
	 ('Problemas de sueño en niños (terrores nocturnos)','Pediátrico',5),
	 ('Miedos y fobias (específicas en niños)','Pediátrico',5),
	 ('Miedos y fobias (sociales en niños)','Pediátrico',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Ansiedad por separación','Pediátrico',5),
	 ('Problemas de socialización (pediátrico)','Pediátrico',5),
	 ('Agresividad (pediátrico)','Pediátrico',5),
	 ('Rabietas frecuentes','Pediátrico',5),
	 ('Problemas dentales (caries en niños)','Pediátrico',5),
	 ('Problemas dentales (dolor dental pediátrico)','Pediátrico',4),
	 ('Problemas dentales (gingivitis en niños)','Pediátrico',5),
	 ('Erupción del pañal','Pediátrico',5),
	 ('Impétigo en niños','Pediátrico',4),
	 ('Molluscum contagiosum','Pediátrico',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Pie plano (pediátrico)','Pediátrico',5),
	 ('Displasia de cadera (control pediátrico)','Pediátrico',5),
	 ('Escoliosis (sospecha en niños)','Pediátrico',5),
	 ('Tics (pediátrico)','Pediátrico',5),
	 ('Encopresis (incontinencia fecal pediátrica)','Pediátrico',5),
	 ('Dolor de oído con fiebre (pediátrico)','Pediátrico',3),
	 ('Conjuntivitis en niños','Pediátrico',4),
	 ('Vómitos y diarrea (gastroenteritis pediátrica)','Pediátrico',3),
	 ('Erupción por calor (sudamina)','Pediátrico',5),
	 ('Urticaria infantil','Pediátrico',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Laringitis (pediátrica)','Pediátrico',3),
	 ('Faringitis estreptocócica (sospecha pediátrica)','Pediátrico',4),
	 ('Escarlatina (sospecha pediátrica)','Pediátrico',3),
	 ('Enfermedad mano-pie-boca','Pediátrico',4),
	 ('Roséola infantil','Pediátrico',4),
	 ('Parotiditis (paperas)','Pediátrico',4),
	 ('Extensión de certificado médico para aprehendido (policial)','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para personal policial','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para justificar ausencia laboral','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para justificar ausencia escolar','Admin - Certificado Médico',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Extensión de certificado médico para trámites deportivos','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para trámites de viaje','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para trámites de licencia de conducir','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para trámites de seguros','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para trámites de adopción','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para trámites de discapacidad','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para trámites judiciales','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para trámites de residencia/migración','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para justificar cuidado de persona dependiente','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para justificar reposo domiciliario','Admin - Certificado Médico',5);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Extensión de certificado médico por alta médica','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico por ingreso hospitalario','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico por enfermedad crónica','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para guarderías/jardines de infancia','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para campamentos de verano','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para actividades recreativas','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para permisos de trabajo específicos','Admin - Certificado Médico',5),
	 ('Extensión de certificado médico para reincorporación laboral','Admin - Certificado Médico',5),
	 ('Detección de Violencia Intrafamiliar (maltrato físico)','Admin - Violencia',3),
	 ('Detección de Violencia Intrafamiliar (maltrato psicológico)','Admin - Violencia',4);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Detección de Violencia Intrafamiliar (maltrato económico)','Admin - Violencia',5),
	 ('Detección de Violencia Intrafamiliar (maltrato sexual)','Admin - Violencia',2),
	 ('Manejo inicial de casos de Violencia Intrafamiliar (contención)','Admin - Violencia',3),
	 ('Manejo inicial de casos de Violencia Intrafamiliar (seguridad)','Admin - Violencia',2),
	 ('Manejo inicial de casos de Violencia Intrafamiliar (documentación)','Admin - Violencia',4),
	 ('Referencia a servicios especializados en Violencia Intrafamiliar','Admin - Violencia',4),
	 ('Detección de Violencia de Género (abuso por pareja/expareja)','Admin - Violencia',3),
	 ('Manejo inicial de casos de Violencia de Género','Admin - Violencia',3),
	 ('Referencia a servicios especializados en Violencia de Género','Admin - Violencia',4),
	 ('Detección de Maltrato Infantil (abuso físico)','Admin - Violencia',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Detección de Maltrato Infantil (abuso emocional)','Admin - Violencia',3),
	 ('Detección de Maltrato Infantil (negligencia)','Admin - Violencia',3),
	 ('Detección de Maltrato Infantil (abuso sexual)','Admin - Violencia',1),
	 ('Notificación de Maltrato Infantil a autoridades competentes','Admin - Violencia',2),
	 ('Referencia a servicios de protección infantil','Admin - Violencia',3),
	 ('Detección de Abuso Sexual (en niños)','Admin - Violencia',1),
	 ('Detección de Abuso Sexual (en adolescentes)','Admin - Violencia',2),
	 ('Detección de Abuso Sexual (en adultos)','Admin - Violencia',2),
	 ('Manejo inicial de casos de Abuso Sexual (contención)','Admin - Violencia',2),
	 ('Manejo inicial de casos de Abuso Sexual (examen forense)','Admin - Violencia',2);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Manejo inicial de casos de Abuso Sexual (profilaxis)','Admin - Violencia',2),
	 ('Referencia a servicios especializados en Abuso Sexual','Admin - Violencia',3),
	 ('Detección de Maltrato a Personas Mayores (abuso físico)','Admin - Violencia',2),
	 ('Detección de Maltrato a Personas Mayores (abuso emocional)','Admin - Violencia',3),
	 ('Detección de Maltrato a Personas Mayores (abuso financiero)','Admin - Violencia',5),
	 ('Detección de Maltrato a Personas Mayores (negligencia)','Admin - Violencia',3),
	 ('Notificación de Maltrato a Personas Mayores a autoridades competentes','Admin - Violencia',3),
	 ('Referencia a servicios de protección a personas mayores','Admin - Violencia',4),
	 ('Violencia Comunitaria (impacto en salud física)','Admin - Violencia',3),
	 ('Violencia Comunitaria (impacto en salud mental)','Admin - Violencia',3);
INSERT INTO SISA_EC.CAT_MOTIVO_CONSULTA_SINTOMAS (Motivo_Consulta_Sintoma,Categoria,Codigo_Triaje) VALUES
	 ('Acoso Escolar (Bullying) - detección de víctimas','Admin - Violencia',4),
	 ('Acoso Escolar (Bullying) - detección de agresores','Admin - Violencia',5),
	 ('Acoso Escolar (Bullying) - asesoramiento a padres','Admin - Violencia',5),
	 ('Ciberacoso (Cyberbullying) - detección','Admin - Violencia',4),
	 ('Ciberacoso (Cyberbullying) - asesoramiento','Admin - Violencia',5),
	 ('Asesoramiento sobre seguridad personal y prevención de violencia','Admin - Violencia',5),
	 ('Apoyo a víctimas de delitos violentos (referencia a apoyo psicológico)','Admin - Violencia',3),
	 ('Apoyo a víctimas de delitos violentos (referencia a apoyo legal)','Admin - Violencia',5),
	 ('Vacunación (BCG Y HB)','Vacunatorio - Emergencia',5),
	 ('Procedimientos de Enfermería (Varios)','Procedimientos - Emergencia',5);
